### ISSUE TITLE
Support for List

### ISSUE THREAD

**Issue by AkshayChordiya** [nhachicha/SnappyDB#33]
Hi, 

This library already looks great, but I have read all the docs you provided but I didn't read anywhere that this library supports any type of List like Array List etc. 

Can you please let me know if it supports? 

Thank you.

**Comment by AkshayChordiya** [comment]
@nhachicha
Thank you so much.

**Comment by AmirAzizi** [comment]
Hi,
can I use this library for nested object (foreign key) 
How can I save them ?
Thank you.

**Comment by SophieKrt** [comment]
Hello, I want to save an ArrayList of objects into the SnappyDB and retrieve it, when necessary. I follow the instructions as given and the arrayList is saved, but when I try to retrieve it from the DB, the error caught is : "Maybe you tried to retrieve an array using this method ? please use getObjectArray instead Class cannot be created (missing no-arg constructor): com.google.gson.JsonPrimitive".
My code is :
public static ArrayList<Research> getOfflineResearches() {
        ArrayList<Research> mySavedResearches = null;
        try {
           mySavedResearches = (ArrayList<Research>) snappy.getObject(Constants.RESEARCHES_OFFLINE, ArrayList.class);

        } catch (SnappydbException e) {
            e.printStackTrace();
        }
        if (mySavedResearches != null) return mySavedResearches;
        return new ArrayList<>();
    }

 Any ideas?

**Comment by davidtcdeveloper** [comment]
@SophieKrt 
How to you save the data? Instead of saving the `ArrayList`, try to convert the list into an array of objects and then convert it back when restoring.
It works this way here.

**Comment by SophieKrt** [comment]
Thank you , I will try to save my objects this way.
