### ISSUE TITLE
Encrypting data

### ISSUE THREAD

**Issue by siga111** [nhachicha/SnappyDB#44]
Is there any solution for data encryption while using SnappyDB? Or at least any ideas how it should/may be done. 
Also, how huge performance impact would be (at least in theory)?
Unfortunatly, Google does not really help.

**Comment by nhachicha** [comment]
Hi @siga111 
Theoretically you can.

You can register a custom [Kryo serializer](https://github.com/EsotericSoftware/kryo#compression-and-encryption) (see [example](https://github.com/nhachicha/SnappyDB/blob/master/snappydb-snippets/app/src/main/java/com/snappydb/snippets/app/activity/snippets/CustomKryoSerializationSnippetActivity.java)) which will give you an `InputStream` & `OutputStream` that you can encrypt/decrypt with a third party library like [Conceal](http://facebook.github.io/conceal/) from [Facebook](https://code.facebook.com/posts/1419122541659395/introducing-conceal-efficient-storage-encryption-for-android/)

**Comment by siga111** [comment]
Thanks, will look into it.
