### ISSUE TITLE
Add dedicated Serializer for java.util.Date

### ISSUE THREAD

**Issue by klaas-loclet** [nhachicha/SnappyDB#46]
Hi there,

thanks for creating SnappyDB, it's absolutely awesome. I'm using it for caching data retrieved from a REST API (wrote a little blog post about first impressions [here](http://klaas-loclet.tumblr.com/post/118370057170/using-snappydb-for-caching)).

At this point, all of my model classes are structured such that Kryo can serialize them nicely (mostly simple POJOs). However, I recently added `java.util.Date` fields to some of them. It turns out that SnappyDB fails to properly store and retrieve them. SnappyDB does not complain when storing the data but throws `Unable to find class: java.util.Date` upon trying to deserialize it.

This seems be due to [this known issue](https://groups.google.com/forum/#!topic/kryo-users/kZacb0ikW98), which - as the Kryo authors point out - is easily remedied by using the custom `DateSerializer` that comes with Kryo. However, SnappyDB does not seem to provide a way to configure this.
My question is thus: Could you enhance SnappyDB so that it would automatically register `java.util.date` fields using
```
kryo.register(Date.class, new DateSerializer());
```
instead of the normal registration?
I believe this is what anybody including a Java date type in their model would want.

**Comment by nhachicha** [comment]
Hi @klaas-loclet  nice blogpost!

did you try to register a custom Kryo Serializer?
```java
snappyDB = new SnappyDB.Builder(getContext())
                .directory(path)
                .registerSerializers(MyCustomObject.class, new MyCustomObjectSerializer())
                .build();
```
Full example: https://github.com/nhachicha/SnappyDB/blob/master/library/src/androidTest/java/com/snappydb/sample/tests/api/BasicOperations.java#L88

The Unit tests uses [`de.javakaffee:kryo-serializers`](https://github.com/magro/kryo-serializers) as an example.

Cheers,

**Comment by klaas-loclet** [comment]
Hey @nhachicha,
thanks for the quick reply - I totally overlooked the builder. I think that solves my issue (I'll test it tomorrow). To me it seems as though adding the `DateSerializer` to SnappyDB out of the box would still make sense as a *sensible default* (as `java.util.Date` is likely to appear in quite a few model classes).
Anyway, thanks again and feel free to close this issue.
