### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by ionuts** [nhachicha/SnappyDB#48]
Let's say that the structure of an object changes in a new version of my app (a new field is added/removed). Is there any way to handle this migration so old data is not lost?

Thank you.

**Comment by nhachicha** [comment]
Hi @ionuts 
Actually this should be handled at `Kryo` level. `SnappyDB` saves only the binary representation of your model
 I suggest your write a unit test to double check this behaviour with your model

Cheers,
