### ISSUE TITLE
Cannot resolve the library in gradle

### ISSUE THREAD

**Issue by magicgoose** [nhachicha/SnappyDB#50]
> Failed to resolve: com.snappydb:snappydb-lib:0.5.2-SNAPSHOT

or

> Failed to resolve: com.snappydb:snappydb-lib:0.5.2

both variants give the same result.

**Comment by nhachicha** [comment]
Hi @magicgoose 
Can you post your gradle config pls

Cheers

**Comment by magicgoose** [comment]
Project:

	buildscript {
	    repositories {
	        jcenter()
	        mavenCentral()

	        maven { url "https://dl.bintray.com/eshteborsch/greenbox" }
	        maven { url "https://oss.sonatype.org/content/repositories/snapshots"}
	    }
	    dependencies {
	        classpath 'com.android.tools.build:gradle:+'
	        classpath 'me.tatarka:gradle-retrolambda:+'
	    }
	}

	allprojects {
	    repositories {
	        jcenter()
	        mavenCentral()

	        maven {
	            url "https://dl.bintray.com/eshteborsch/greenbox"
	        }
	    }
	}

Module:

	tasks.whenTaskAdded { task ->
	    if (task.name.startsWith("lint")) {
	        task.enabled = false
	    }
	}

	apply plugin: 'com.android.application'
	apply plugin: 'me.tatarka.retrolambda'

	retrolambda {
	    jvmArgs '-noverify'
	}

	android {
	    compileSdkVersion 22
	    buildToolsVersion "22.0.1"

	    defaultConfig {
	        applicationId "some.package"
	        minSdkVersion 10
	        targetSdkVersion 22
	        versionCode 2
	        versionName "1.1.0"
	    }
	    buildTypes {
	        release {
	            minifyEnabled true
	            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
	        }
	        debug {
	            minifyEnabled true
	            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-rules-debug.pro'
	        }
	    }

	    productFlavors {
	        fTestServer
	        fProductionServer
	    }

	    compileOptions {
	        sourceCompatibility JavaVersion.VERSION_1_8
	        targetCompatibility JavaVersion.VERSION_1_8
	    }

	    packagingOptions {
	        exclude 'META-INF/DEPENDENCIES.txt'
	        exclude 'META-INF/NOTICE'
	        exclude 'META-INF/NOTICE.txt'
	        exclude 'META-INF/LICENSE'
	        exclude 'META-INF/LICENSE.txt'
	    }

	    lintOptions {
	        abortOnError false
	    }

	    // http://stackoverflow.com/a/21020469/1418097
	    signingConfigs {
	        release {
	            storeFile file(RELEASE_STORE_FILE)
	            storePassword RELEASE_STORE_PASSWORD
	            keyAlias RELEASE_KEY_ALIAS
	            keyPassword RELEASE_KEY_PASSWORD
	        }
	    }

	    buildTypes {
	        release {
	            signingConfig signingConfigs.release
	        }
	    }
	}

	dependencies {
	    compile fileTree(dir: 'libs', include: ['*.jar'])
	    compile 'com.android.support:appcompat-v7:22.2.0'
	    compile 'greenbox:android-toolkit:0.4.4'
	    compile 'com.google.code.gson:gson:2.+'
	    compile 'com.avast:android-styled-dialogs:+'
	    compile 'com.pnikosis:materialish-progress:1.5'
	    compile 'com.android.support:recyclerview-v7:+'
	    compile 'com.yqritc:recyclerview-flexibledivider:1.2.4'
	    compile 'com.jakewharton.timber:timber:3.0.2'
	    compile 'com.google.android.gms:play-services-maps:7.+'
	    compile 'com.google.android.gms:play-services-analytics:7.+'
	    compile 'com.google.android.gms:play-services-location:7.+'

	    compile 'com.github.navasmdc:MaterialDesign:1.5@aar'
	    compile 'com.jpardogo.materialtabstrip:library:1.0.9'
	    compile 'com.mikepenz.materialdrawer:library:2.9.7@aar'
	    compile 'com.mikepenz.iconics:library:0.7.9@aar'
	    compile 'com.mikepenz.iconics:community-material-typeface:1.0.0@aar'
	    compile 'com.github.ryanjohn1:onboarding:1.0.3'

	    compile 'joda-time:joda-time:+'
	    compile 'com.fatboyindustrial.gson-jodatime-serialisers:gson-jodatime-serialisers:+'
	}

If I add the dependencies to that dependencies list, the `com.snappydb:snappydb-lib:0.5.2` does not resolve. OTOH, other dependencies are fine.

**Comment by koustuvsinha** [comment]
:+1: same issue here

**Comment by nhachicha** [comment]
Hi @magicgoose @koustuvsinha 

just pushed the `0.5.2` release to Sonatype, it should be synced to maven central in an hour or two

Cheers,

**Comment by koustuvsinha** [comment]
yes issue resolved. Great library btw :)
