### ISSUE TITLE
NoSuchMethodError exception when trying to open the database

### ISSUE THREAD

**Issue by chenhx37** [nhachicha/SnappyDB#54]
Hi,
I'm trying to use snappydb but some problems occurs.
my code is:

	public void TrySnappy() throws SnappydbException{
		DB snappydb = DBFactory.open(this.getBaseContext());
	}

but this exception is thrown:
java.lang.NoSuchMethodError: com.esotericsoftware.kryo.Kryo.setAsmEnabled
	at com.snappydb.internal.DBImpl.<init>(DBImpl.java:51)
	at com.snappydb.DBFactory.open(DBFactory.java:40)
	at com.snappydb.DBFactory.open(DBFactory.java:65)
	at com.snappydb.DBFactory.open(DBFactory.java:77)
......
thanks

**Comment by chenhx37** [comment]
Well,I solved it.
I think it's better to add all necessary jars into the documents.
Actually we also need:
objenesis-1.2.jar
kryo-2.24.0.jar
minlog-1.2.jar

**Comment by nhachicha** [comment]
Hi @chenhx37 
this should happen automatically when you pull `compile 'com.esotericsoftware.kryo:kryo:2.24.0'` dependencies.
Cheers

**Comment by chenhx37** [comment]
Yes,actually at first I didn't know I need 3 more jars to get it running.I'm a beginner and have never met this kind of problems before.But thank god and thank you,it works fine now!
