### ISSUE TITLE
On Network call response data stores successfully but not present  while reading.  

### ISSUE THREAD

**Issue by sujeet-kumar-mehta** [nhachicha/SnappyDB#77]
I am making a network call through volley. On Response success I am trying to store data through SnappyDb which shows that it has stored successfully. But while reading any data is not present. But if I have data outside of response than it saves. Below is my code. I am struggling in this from last 2 days. Your help will be highly appreciated. Thanks   

private void makeApiCall(String key) {
        if (Utility.isNetworkAvailable(AddCustomerActivity.this)) {
            final String finalKey = key;
            showProgressDailog("Adding...");
            NetworkEb.getInstance().apiCallAddUser(customerEb, (key != null && !key.contains(":"))? true : false, new OnJsonResponse() {
                @Override
                public void onSuccess(JSONObject response) {

                    try {
                        int serverId = response.getInt("id");
                        customerEb.setKey(serverId + "");
                        customerEb.setSync(true);
                        snappyDbUtil.saveObjectFromKey("customer", DbName.CUSTOMER.name(), customerEb);
} catch (JSONException e) {
                        e.printStackTrace();
                    }
                }

                @Override
                public void onError(String response) {
                    Utility.showToast("Upload failed! Try Again");
                    progressDialog.dismiss();

                }
            });
        } else {
            if (key == null) {
                key = snappyDbUtil.getNewKey(DbName.CUSTOMER.name());
                customerEb.setKey(key);
                customerEb.setSync(false);
                Utility.showToast("Saved locally");

            }
            snappyDbUtil.saveObjectFromKey(key, DbName.CUSTOMER.name(), customerEb);
        }

**Comment by ezyclie** [comment]
I am having same issue here too, this is intermittent somehow

**Comment by sujeet-kumar-mehta** [comment]
@ezyclie  thanks for writing here. Did you had any success in saving the data with this approach. @SalomonBrys @nhachicha plz help this has become show stopper in our progress. Thanks

**Comment by sujeet-kumar-mehta** [comment]
Hi @ezyclie  I found a solution for this. You need to save the data in UI thread by calling this 
runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                itemDataModel.setKey("ITEMS:" + key);
                                itemDataModel.setSync(true);
                                snappyDbUtil.saveObjectFromKey(itemDataModel.getKey(), DbName.ITEMS.name(), itemDataModel);
                            }
                        });

Here you have to also care for the keys to store with which only saves if we provide a db name as shown in the above code.
